import { GithubIcon, LinkedinIcon, TwitterIcon, InstagramIcon, ExternalLinkIcon } from './components/IconComponents';

// ===================================================================================
//
//  THIS FILE WAS AUTO-GENERATED BY THE 'customize.js' SCRIPT.
//
//  To update your profile, edit the `userData` object in `customize.js`
//  and run `node customize.js` in your terminal.
//
//  DO NOT EDIT THIS FILE MANUALLY.
//
// ===================================================================================

export const profile = {
  "name": "Alex Doe",
  "title": "Full-Stack Developer & UI/UX Enthusiast",
  "bio": "Crafting beautiful, functional, and user-centric digital experiences. Turning complex problems into elegant solutions.",
  "avatarUrl": "https://picsum.photos/id/237/200/200"
};

export const cvUrl = `#`;

export const contactEmail = `hello@example.com`;

export const socials = [
  { name: "GitHub", url: "https://github.com", icon: GithubIcon },
  { name: "LinkedIn", url: "https://linkedin.com", icon: LinkedinIcon },
  { name: "Twitter", url: "https://twitter.com", icon: TwitterIcon },
  { name: "Instagram", url: "https://instagram.com", icon: InstagramIcon }
];

export const aboutMe = `
Hello! I'm Alex, a passionate developer with a knack for creating dynamic and responsive web applications.
  With over 5 years of experience in the tech industry, I've had the privilege of working on a variety of projects, from small business websites to large-scale enterprise applications.
  My expertise lies in the MERN stack (MongoDB, Express, React, Node.js), but I'm always eager to learn new technologies and expand my skillset.
  When I'm not coding, you can find me hiking in the mountains, experimenting with new recipes, or capturing moments with my camera.
  I believe in the power of technology to connect people and solve real-world problems. Let's build something amazing together!
`;

export const skills = {
  "Frontend": [
    "React",
    "TypeScript",
    "Tailwind CSS",
    "Next.js",
    "Vite"
  ],
  "Backend": [
    "Node.js",
    "Express",
    "MongoDB",
    "PostgreSQL",
    "REST APIs"
  ],
  "Tools & Other": [
    "Git",
    "Docker",
    "Figma",
    "CI/CD",
    "Jest"
  ]
};

export const workExperience = [
  {
    "role": "Senior Frontend Developer",
    "company": "Tech Solutions Inc.",
    "duration": "Jan 2021 - Present",
    "description": "Led the development of a new client-facing dashboard using React and TypeScript. Improved application performance by 30% and mentored junior developers."
  },
  {
    "role": "Full-Stack Developer",
    "company": "Innovate Co.",
    "duration": "Jun 2018 - Dec 2020",
    "description": "Developed and maintained full-stack web applications for various clients. Worked with Node.js on the backend and React on the frontend."
  },
  {
    "role": "Junior Web Developer",
    "company": "Digital Creations",
    "duration": "Jul 2016 - May 2018",
    "description": "Assisted in building and maintaining marketing websites using HTML, CSS, and JavaScript. Gained foundational experience in web development and version control."
  }
];

export const projects = [
  {
    "title": "E-commerce Platform",
    "description": "A full-featured e-commerce site with user authentication, product catalog, and a Stripe-integrated checkout process.",
    "tech": [
      "Next.js",
      "MongoDB",
      "Stripe",
      "Tailwind CSS"
    ],
    "imageUrl": "https://picsum.photos/id/1015/800/600",
    "liveUrl": "#",
    "repoUrl": "#"
  },
  {
    "title": "Project Management Tool",
    "description": "A collaborative tool for teams to manage tasks, track progress, and communicate effectively, featuring a drag-and-drop interface.",
    "tech": [
      "React",
      "Node.js",
      "Socket.IO",
      "PostgreSQL"
    ],
    "imageUrl": "https://picsum.photos/id/1018/800/600",
    "liveUrl": "#",
    "repoUrl": "#"
  },
  {
    "title": "Personal Blog",
    "description": "A content-focused blog platform with a Markdown editor and static site generation for optimal performance and SEO.",
    "tech": [
      "Vite",
      "React",
      "Markdown",
      "Firebase"
    ],
    "imageUrl": "https://picsum.photos/id/1025/800/600",
    "liveUrl": "#",
    "repoUrl": "#"
  }
];

export const galleryImages = [
  {
    "src": "https://picsum.photos/id/10/800/600",
    "alt": "Misty forest path"
  },
  {
    "src": "https://picsum.photos/id/20/800/600",
    "alt": "City skyline at dusk"
  },
  {
    "src": "https://picsum.photos/id/30/800/600",
    "alt": "Hot air balloons over a valley"
  },
  {
    "src": "https://picsum.photos/id/40/800/600",
    "alt": "Person walking on a beach"
  },
  {
    "src": "https://picsum.photos/id/50/800/600",
    "alt": "Abstract architectural details"
  },
  {
    "src": "https://picsum.photos/id/60/800/600",
    "alt": "A cat looking curiously"
  }
];

export const videoUrl = `https://www.youtube.com/embed/dQw4w9WgXcQ?si=bTeF-4b7g_f3hE8d`;

export const testimonials = [
  {
    "id": 1,
    "name": "Sarah Johnson",
    "role": "Product Manager",
    "company": "Tech Corp",
    "avatarUrl": "https://picsum.photos/id/64/200/200",
    "content": "Working with Alex was an absolute pleasure. Their attention to detail and ability to translate complex requirements into elegant solutions is remarkable. They delivered our project ahead of schedule with exceptional quality.",
    "rating": 5
  },
  {
    "id": 2,
    "name": "Michael Chen",
    "role": "CTO",
    "company": "StartupHub",
    "avatarUrl": "https://picsum.photos/id/65/200/200",
    "content": "Alex is a talented developer who brings both technical expertise and creative problem-solving to every project. Their code is clean, well-documented, and maintainable. I highly recommend them for any development work.",
    "rating": 5
  },
  {
    "id": 3,
    "name": "Emily Rodriguez",
    "role": "Design Lead",
    "company": "Creative Agency",
    "avatarUrl": "https://picsum.photos/id/66/200/200",
    "content": "The collaboration with Alex was fantastic. They have a great eye for design implementation and always ensure the final product matches our vision perfectly. Their responsive designs work flawlessly across all devices.",
    "rating": 5
  }
];
