# Netlify configuration file
# This file configures how Netlify builds and deploys your site

[build]
  # Directory to change to before starting build
  base = "/"
  
  # Build command - this runs when Netlify builds your site
  command = "npm run build"
  
  # Directory that contains the deploy-ready files
  publish = "dist"
  
  # Node.js version for the build environment
  environment = { NODE_VERSION = "18" }

# Production context: All deploys from the main branch
[context.production]
  environment = { NODE_ENV = "production" }

# Headers for better security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Permissions Policy
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache control for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect rules (if needed in future)
# [[redirects]]
#   from = "/old-path"
#   to = "/new-path"
#   status = 301

# SPA routing support - all routes go to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Custom 404 page (falls back to index.html for SPA)
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 404
